[[main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/paulluneaug"
  weight = 30

[[main]]
  pre = "itchio"
  name = "Itchio"
  url = "https://paulluneau.itch.io/"
  weight = 40