baseURL = 'https://paulluneaug.github.io/'
languageCode = 'en-us'
title = 'Paul Luneau'
theme = 'brewmCustom'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.global]]
    identifier = 'portfolio'
    name       = 'Portfolio'
    url        = '/portfolio/'
    weight     = 1
  [[menus.global]]
    identifier = 'about'
    name       = 'About'
    url        = '/about/'
    weight     = 1


[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error
